In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
import os

os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\prediction_models\\csv_for_stacking')

from helper_functions import *

In [20]:
os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\data')

# Read data
train_data = pd.read_pickle("./data_base_train.pkl")
train_data = train_data.fillna(method='ffill', axis=0)
train_data.columns = train_data.columns.droplevel()
train_data.head()

C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)

PRICE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,...,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE
DATE,,,,,,,,,,,,,,,,,,,,,
1990-01-02,77300.0,77400.0,77020.0,77020.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,383113.9383,383155.65,382988.9700,382988.97
1990-01-03,76890.0,77030.0,76700.0,76740.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,382863.9600,383030.64,382863.9600,382905.63
1990-01-04,77080.0,77610.0,77000.0,77490.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,382947.3000,383072.31,382947.3000,383030.64
1990-01-05,77050.0,77280.0,76980.0,76980.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,383238.9900,383280.66,383155.6500,383155.65
1990-01-08,77280.0,77300.0,77090.0,77200.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,383113.9383,383197.32,383113.9383,383197.32

In [21]:
# Read data
test_data = pd.read_pickle("./data_base_test.pkl")
test_data = test_data.fillna(method='ffill', axis=0)
test_data.columns = test_data.columns.droplevel()
test_data.tail()

C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)

PRICE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,...,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE
DATE,,,,,,,,,,,,,,,,,,,,,
2017-12-25,77000.0,77200.0,76990.0,77130.0,109810.0,109880.0,109340.0,109680.0,8540.0,8560.0,...,31580.0,31620.0,123965.0,124215.0,123645.0,123835.0,411293.3175,411293.3175,411282.900,411293.3175
2017-12-26,77160.0,77310.0,77120.0,77270.0,109810.0,109880.0,109340.0,109680.0,8750.0,8750.0,...,31580.0,31620.0,123895.0,123990.0,123535.0,123960.0,411293.3175,411293.3175,411282.900,411282.9000
2017-12-27,77260.0,77790.0,77240.0,77740.0,109420.0,109970.0,109260.0,109700.0,8810.0,8810.0,...,31590.0,31640.0,123960.0,124105.0,123810.0,124005.0,410595.3450,410616.1800,410595.345,410616.1800
2017-12-28,77690.0,78090.0,77680.0,77940.0,108940.0,109020.0,108940.0,109020.0,8750.0,8770.0,...,31500.0,31520.0,123955.0,124200.0,123920.0,124055.0,410616.1800,410637.0150,410616.180,410616.1800
2017-12-29,77960.0,78250.0,77880.0,78090.0,108520.0,108520.0,108520.0,108520.0,8800.0,8830.0,...,31410.0,31480.0,124040.0,124430.0,123335.0,123395.0,410616.1800,410637.0150,410616.180,410616.1800

In [22]:
# Read stack data
stack_data = pd.read_pickle("./data_stack_test.pkl")
stack_data = stack_data.fillna(method='ffill', axis=0)
stack_data.columns = stack_data.columns.droplevel()
stack_data.tail()

C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)

PRICE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,...,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE
DATE,,,,,,,,,,,,,,,,,,,,,
2018-12-25,70450.0,70750.0,70440.0,70570.0,96200.0,96710.0,95600.0,95620.0,7810.0,7810.0,...,27000.0,27150.0,111895.0,112860.0,108405.0,108485.0,407220.075,407220.075,407209.6575,407220.075
2018-12-26,70490.0,70790.0,70390.0,70760.0,96200.0,96710.0,95600.0,95620.0,7750.0,7800.0,...,27000.0,27150.0,108650.0,114845.0,107260.0,114680.0,407220.075,407220.075,407209.6575,407220.075
2018-12-27,70730.0,70850.0,70250.0,70420.0,97000.0,97390.0,94370.0,94800.0,7790.0,7790.0,...,26470.0,26900.0,114375.0,116000.0,111210.0,115755.0,406678.365,406740.870,406678.3650,406720.035
2018-12-28,70370.0,70780.0,70360.0,70480.0,94790.0,97170.0,94440.0,96910.0,7770.0,7780.0,...,26870.0,27230.0,115590.0,116860.0,114785.0,115075.0,406699.200,406720.035,406678.3650,406678.365
2018-12-31,70520.0,70800.0,70420.0,70540.0,97210.0,97870.0,96940.0,97600.0,7740.0,7740.0,...,26870.0,27230.0,115670.0,116760.0,115450.0,116565.0,406678.365,406699.200,406657.5300,406699.200

In [23]:
# All 88 futures
futures = ['F_AD','F_AE','F_AH','F_AX','F_BC','F_BG','F_BO','F_BP',
               'F_C','F_CA','F_CC','F_CD','F_CF','F_CL','F_CT','F_DL',             
               'F_DM','F_DT','F_DX','F_DZ','F_EB','F_EC','F_ED','F_ES',
               'F_F','F_FB','F_FC','F_FL','F_FM','F_FP','F_FV','F_FY',             
               'F_GC','F_GD','F_GS','F_GX','F_HG','F_HO','F_HP','F_JY',
              'F_KC','F_LB','F_LC','F_LN','F_LQ','F_LR','F_LU','F_LX',
           'F_MD','F_MP','F_ND','F_NG','F_NQ','F_NR','F_NY','F_O',
             'F_OJ','F_PA','F_PL','F_PQ','F_RB','F_RF','F_RP','F_RR',
               'F_RU','F_RY','F_S','F_SB','F_SF','F_SH','F_SI','F_SM',
             'F_SS','F_SX','F_TR','F_TU','F_TY','F_UB','F_US','F_UZ',
            'F_VF','F_VT','F_VW','F_VX','F_W','F_XX','F_YM','F_ZQ']
len(futures)

88

In [24]:
# indicator data
indicator_train = pd.read_pickle("./data_indicators_base_train.pkl")
indicator_test = pd.read_pickle("./data_indicators_base_test.pkl")
indicator_stack = pd.read_pickle("./data_indicators_stack_test.pkl")

In [25]:
# Create correlation matrix
corr_matrix = indicator_train.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find index of feature columns with correlation less than 0.4
to_drop = [column for column in upper.columns if any(upper[column] > 0.4)]

indicator_train = indicator_train.drop(to_drop, axis=1)
indicator_test = indicator_test.drop(to_drop, axis=1)
indicator_stack = indicator_stack.drop(to_drop, axis=1)

indicator_train = indicator_train.fillna(method='bfill', axis=0)
indicator_test = indicator_test.fillna(method='bfill', axis=0)
indicator_stack = indicator_stack.fillna(method='bfill', axis=0)

In [26]:
new_features = pd.DataFrame(index=np.arange(len(test_data)+len(stack_data)), columns=np.arange(88))
new_features.columns = futures
new_features["dates"] = (list(test_data.index) + list(stack_data.index))
new_features = new_features.set_index("dates")
new_features.head()

,F_AD,F_AE,F_AH,F_AX,F_BC,F_BG,F_BO,F_BP,F_C,F_CA,...,F_US,F_UZ,F_VF,F_VT,F_VW,F_VX,F_W,F_XX,F_YM,F_ZQ
dates,,,,,,,,,,,,,,,,,,,,,
2016-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
from sklearn.preprocessing import StandardScaler
import lightgbm as lgb

os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\prediction_models\\LGBM_saved_models')

scaler = StandardScaler()

count = 0

# Build separate LGBM models for each individual future
for fut in futures:
    
    # Lag features by 1 day
    x_train = train_data.shift(1).iloc[:,count:(count+4)]
    # combine with indicators
    combined_train = pd.concat([x_train, indicator_train], axis=1)
    combined_train = combined_train.dropna(axis=0)
    x_train = combined_train.iloc[:,0:4]
    x_train_exog = combined_train.iloc[:,4:]
    y_train = train_data.iloc[:,(count+3)]
    y_train = y_train.dropna(axis=0)
    y_train = y_train.drop(y_train.index[0])
    y_train = y_train.reset_index()
    train_dates = y_train.iloc[:,0]
    y_train = y_train.iloc[:,1]

    x_test = test_data.shift(1).iloc[:,count:(count+4)]
    combined_test = pd.concat([x_test, indicator_test], axis=1)
    combined_test = combined_test.dropna(axis=0)
    x_test = x_test.dropna(axis=0)
    x_test = combined_test.iloc[:,0:4]
    x_test_exog = combined_test.iloc[:,4:]
    y_test = test_data.iloc[:,(count+3)]
    y_test = y_test.dropna(axis=0)
    y_test = y_test.drop(y_test.index[0])
    y_test = y_test.reset_index()
    test_dates = y_test.iloc[:,0]
    y_test = y_test.iloc[:,1]

    x_stack = stack_data.shift(1).iloc[:,count:(count+4)]
    combined_stack = pd.concat([x_stack, indicator_stack], axis=1)
    combined_stack = combined_stack.dropna(axis=0)
    x_stack = x_stack.dropna(axis=0)
    x_stack = combined_stack.iloc[:,0:4]
    x_stack_exog = combined_stack.iloc[:,4:]
    y_stack = stack_data.iloc[:,(count+3)]
    y_stack = y_stack.dropna(axis=0)
    y_stack = y_stack.drop(y_stack.index[0])
    y_stack = y_stack.reset_index()
    stack_dates = y_stack.iloc[:,0]
    y_stack = y_stack.iloc[:,1]

    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)
    x_stack = scaler.transform(x_stack)

    d_train = lgb.Dataset(x_train, label=y_train)

    #Set model params
    params = {}
    params['learning_rate'] = 0.5          
    params['boosting_type'] = 'gbdt'
    params['objective'] = 'regression'
    params['metric'] = 'mse'
    params['sub_feature'] = 0.8
    params['num_leaves'] = 20               
    params['min_data'] = 20
    params['max_depth'] = 20

    lgbmodel = lgb.train(params, d_train, 100)
    
    #Save models
    filename = fut + ".txt"
    lgbmodel.save_model(filename)

    #Predictions
    y_pred = lgbmodel.predict(x_test)
    stack_pred = lgbmodel.predict(x_stack)

    #Store predictions to use for stack model
    for i in range(len(y_pred)):
        new_features.at[test_dates[i], fut] = y_pred[i]
    for j in range(len(stack_pred)):
        new_features.at[stack_dates[j], fut] = stack_pred[j]

    count = count + 4
    
    print('Mean Absolute Error for ', fut, ': ', mean_absolute_percentage_error(y_test, y_pred))  
    print('Root Mean Squared Error for ', fut, ': ', rmse_ratio(y_test, y_pred))

Mean Absolute Error for  F_AD :  0.49676566044671394
Root Mean Squared Error for  F_AD :  1.7620163043216994
Mean Absolute Error for  F_AE :  0.7788526687844781
Root Mean Squared Error for  F_AE :  3.2111108999550098
Mean Absolute Error for  F_AH :  1.3273591622460996
Root Mean Squared Error for  F_AH :  1.5929225052313782
Mean Absolute Error for  F_AX :  2.522208552428244
Root Mean Squared Error for  F_AX :  20.346916154235785
Mean Absolute Error for  F_BC :  1.8371360684433595
Root Mean Squared Error for  F_BC :  5.228910462315504
Mean Absolute Error for  F_BG :  1.7019665465871914
Root Mean Squared Error for  F_BG :  4.601521757325772
Mean Absolute Error for  F_BO :  0.9713082167825953
Root Mean Squared Error for  F_BO :  1.7931387559764884
Mean Absolute Error for  F_BP :  6.434175900886448
Root Mean Squared Error for  F_BP :  21.80122006917509
Mean Absolute Error for  F_C :  1.1185757562769105
Root Mean Squared Error for  F_C :  1.9557499290894718
Mean Absolute Error for  F_CA :  0.8383582559933729
Root Mean Squared Error for  F_CA :  2.5182489739007767
Mean Absolute Error for  F_CC :  1.3652325786327792
Root Mean Squared Error for  F_CC :  2.998889125063606
Mean Absolute Error for  F_CD :  0.4382980375482094
Root Mean Squared Error for  F_CD :  1.562435042948653
Mean Absolute Error for  F_CF :  0.4479636443515838
Root Mean Squared Error for  F_CF :  2.5938204844795574
Mean Absolute Error for  F_CL :  1.7676902611871808
Root Mean Squared Error for  F_CL :  4.930827444134184
Mean Absolute Error for  F_CT :  0.961661092903988
Root Mean Squared Error for  F_CT :  2.764754235034726
Mean Absolute Error for  F_DL :  0.9411633472790001
Root Mean Squared Error for  F_DL :  2.4716170983885153
Mean Absolute Error for  F_DM :  7.565741574413641
Root Mean Squared Error for  F_DM :  37.04183653957772
Mean Absolute Error for  F_DT :  2.168523800056831
Root Mean Squared Error for  F_DT :  9.789111609891721
Mean Absolute Error for  F_DX :  0.35813738818118
Root Mean Squared Error for  F_DX :  1.4659590001541523
Mean Absolute Error for  F_DZ :  8.85772571889656
Root Mean Squared Error for  F_DZ :  20.759160464178034
Mean Absolute Error for  F_EB :  0.13385422124398388
Root Mean Squared Error for  F_EB :  0.6923646334971258
Mean Absolute Error for  F_EC :  0.4500653498997869
Root Mean Squared Error for  F_EC :  2.1858512296603387
Mean Absolute Error for  F_ED :  0.022084613151269732
Root Mean Squared Error for  F_ED :  0.15608769450987428
Mean Absolute Error for  F_ES :  7.490139507315549
Root Mean Squared Error for  F_ES :  35.08808325908912
Mean Absolute Error for  F_F :  0.016268018047058137
Root Mean Squared Error for  F_F :  0.11057846120357481
Mean Absolute Error for  F_FB :  1.351439792986526
Root Mean Squared Error for  F_FB :  1.669015622224375
Mean Absolute Error for  F_FC :  1.1233485951510227
Root Mean Squared Error for  F_FC :  3.941053524234448
Mean Absolute Error for  F_FL :  1.3531083998799371
Root Mean Squared Error for  F_FL :  5.200238582858297
Mean Absolute Error for  F_FM :  2.297761725588374
Root Mean Squared Error for  F_FM :  4.746044018428427
Mean Absolute Error for  F_FP :  5.061187423232904
Root Mean Squared Error for  F_FP :  13.565768052155871
Mean Absolute Error for  F_FV :  0.13931666220251257
Root Mean Squared Error for  F_FV :  0.6148382675403302
Mean Absolute Error for  F_FY :  0.7805724947728401
Root Mean Squared Error for  F_FY :  1.41384856762574
Mean Absolute Error for  F_GC :  0.6823437157375932
Root Mean Squared Error for  F_GC :  3.252360902794092
Mean Absolute Error for  F_GD :  1.100090610273612
Root Mean Squared Error for  F_GD :  4.302519967115597
Mean Absolute Error for  F_GS :  0.5166418595414729
Root Mean Squared Error for  F_GS :  2.6832074804499624
Mean Absolute Error for  F_GX :  2.1517680973322677
Root Mean Squared Error for  F_GX :  15.237033546683879
Mean Absolute Error for  F_HG :  1.1102564954696859
Root Mean Squared Error for  F_HG :  3.608604115151826
Mean Absolute Error for  F_HO :  1.7029226649985554
Root Mean Squared Error for  F_HO :  5.546599732021528
Mean Absolute Error for  F_HP :  2.8188989621928373
Root Mean Squared Error for  F_HP :  6.032446759129072
Mean Absolute Error for  F_JY :  0.5198851371056449
Root Mean Squared Error for  F_JY :  2.3756036147305926
Mean Absolute Error for  F_KC :  1.2141296537607296
Root Mean Squared Error for  F_KC :  3.745106757043854
Mean Absolute Error for  F_LB :  1.237237307555273
Root Mean Squared Error for  F_LB :  3.061671573187641
Mean Absolute Error for  F_LC :  1.0702378324006956
Root Mean Squared Error for  F_LC :  3.1059910334414464
Mean Absolute Error for  F_LN :  1.6659432761758797
Root Mean Squared Error for  F_LN :  4.367625168788206
Mean Absolute Error for  F_LQ :  1.6417764301574613
Root Mean Squared Error for  F_LQ :  5.924003585073433
Mean Absolute Error for  F_LR :  1.1176233651601046
Root Mean Squared Error for  F_LR :  2.5819159117124926
Mean Absolute Error for  F_LU :  1.8277117544302914
Root Mean Squared Error for  F_LU :  6.202857641753435
Mean Absolute Error for  F_LX :  2.8043940453237446
Root Mean Squared Error for  F_LX :  9.89605645239096
Mean Absolute Error for  F_MD :  7.356306779532461
Root Mean Squared Error for  F_MD :  40.37414192158527
Mean Absolute Error for  F_MP :  9.667010549959274
Root Mean Squared Error for  F_MP :  17.885908681702876
Mean Absolute Error for  F_ND :  0.5677474328627212
Root Mean Squared Error for  F_ND :  1.9484566014311828
Mean Absolute Error for  F_NG :  1.9608068369603344
Root Mean Squared Error for  F_NG :  4.310881002400106
Mean Absolute Error for  F_NQ :  10.322455979348783
Root Mean Squared Error for  F_NQ :  48.142663635528194
Mean Absolute Error for  F_NR :  1.0995554509757623
Root Mean Squared Error for  F_NR :  2.109620455989515
Mean Absolute Error for  F_NY :  0.9788767055373007
Root Mean Squared Error for  F_NY :  4.076989247555474
Mean Absolute Error for  F_O :  1.575206486415868
Root Mean Squared Error for  F_O :  2.191675382247476
Mean Absolute Error for  F_OJ :  1.7141417637397263
Root Mean Squared Error for  F_OJ :  3.8814556194026197
Mean Absolute Error for  F_PA :  1.7761202286312647
Root Mean Squared Error for  F_PA :  6.682959404811747
Mean Absolute Error for  F_PL :  1.0935160703157392
Root Mean Squared Error for  F_PL :  3.2101797670933454
Mean Absolute Error for  F_PQ :  1.0775875984391008
Root Mean Squared Error for  F_PQ :  3.1925952989627087
Mean Absolute Error for  F_RB :  1.896071933128474
Root Mean Squared Error for  F_RB :  6.351825073474642
Mean Absolute Error for  F_RF :  0.7519817384384677
Root Mean Squared Error for  F_RF :  4.2686711069081635
Mean Absolute Error for  F_RP :  0.5135366494309163
Root Mean Squared Error for  F_RP :  2.2335792276713664
Mean Absolute Error for  F_RR :  1.848572186497836
Root Mean Squared Error for  F_RR :  2.5573597305897655
Mean Absolute Error for  F_RU :  6.155766927509251
Root Mean Squared Error for  F_RU :  31.05684582888809
Mean Absolute Error for  F_RY :  0.541854541032241
Root Mean Squared Error for  F_RY :  29.260313792145105
Mean Absolute Error for  F_S :  0.9505636297051383
Root Mean Squared Error for  F_S :  2.8765110195632353
Mean Absolute Error for  F_SB :  1.5389016844709695
Root Mean Squared Error for  F_SB :  3.192594180822033
Mean Absolute Error for  F_SF :  0.4134988003110236
Root Mean Squared Error for  F_SF :  1.9434501461418177
Mean Absolute Error for  F_SH :  8.21454251262019
Root Mean Squared Error for  F_SH :  18.657527020404462
Mean Absolute Error for  F_SI :  1.105606317160899
Root Mean Squared Error for  F_SI :  4.481610336807881
Mean Absolute Error for  F_SM :  1.135790237791806
Root Mean Squared Error for  F_SM :  2.8208709673945425
Mean Absolute Error for  F_SS :  0.06250574978730167
Root Mean Squared Error for  F_SS :  0.30154053439105144
Mean Absolute Error for  F_SX :  0.7182907804579267
Root Mean Squared Error for  F_SX :  2.7204896539015087
Mean Absolute Error for  F_TR :  1.9666859303934445
Root Mean Squared Error for  F_TR :  5.038886977148688
Mean Absolute Error for  F_TU :  0.05412032638312243
Root Mean Squared Error for  F_TU :  0.32733788753206866
Mean Absolute Error for  F_TY :  0.2340404696547157
Root Mean Squared Error for  F_TY :  1.0810490459153692

Mean Absolute Error for  F_UB :  0.7735290493122079
Root Mean Squared Error for  F_UB :  3.60309206805996
Mean Absolute Error for  F_US :  1.064961303417003
Root Mean Squared Error for  F_US :  7.237883679432677
Mean Absolute Error for  F_UZ :  0.4060891765931206
Root Mean Squared Error for  F_UZ :  1.4727769540791071
Mean Absolute Error for  F_VF :  0.4792838986241584
Root Mean Squared Error for  F_VF :  2.446250296513432
Mean Absolute Error for  F_VT :  0.47461454281409493
Root Mean Squared Error for  F_VT :  3.092938136713294
Mean Absolute Error for  F_VW :  0.11234704643361204
Root Mean Squared Error for  F_VW :  0.44403929512292745
Mean Absolute Error for  F_VX :  3.5564539937000728
Root Mean Squared Error for  F_VX :  6.578765079241691
Mean Absolute Error for  F_W :  1.3015225723710477
Root Mean Squared Error for  F_W :  2.561485068810878
Mean Absolute Error for  F_XX :  0.8088623360328774
Root Mean Squared Error for  F_XX :  1.891254117152045
Mean Absolute Error for  F_YM :  8.929911327837583
Root Mean Squared Error for  F_YM :  40.60314091066654
Mean Absolute Error for  F_ZQ :  0.04692039888491935
Root Mean Squared Error for  F_ZQ :  0.41623268736180513

In [11]:
print('Mean Absolute Error:', mean_absolute_percentage_error(np.concatenate([y_test, y_stack], axis=0), np.concatenate([y_pred, stack_pred], axis=0)))  
print('Root Mean Squared Error:', rmse_ratio(np.concatenate([y_test, y_stack], axis=0), np.concatenate([y_pred, stack_pred], axis=0)))

Mean Absolute Error: 0.04454404960359842
Root Mean Squared Error: 0.3951319493281057

In [13]:
os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\prediction_models\\csv_for_stacking')
new_features.to_csv("LGBM_Predictions.csv")

In [50]:
os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\data')

# Read 2019 data
pred_data = pd.read_pickle("./2019_test_85tickers.pkl")
pred_data = pred_data.fillna(method='ffill', axis=0)
pred_data.columns = pred_data.columns.droplevel()
pred_data = pred_data.iloc[131:,:]
pred_data.head()

PRICE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,...,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE,OPEN,HIGH,LOW,CLOSE
DATE,,,,,,,,,,,,,,,,,,,,,
2019-01-01,70520.0,70800.0,70420.0,70540.0,97210.0,97870.0,96940.0,97600.0,7740.0,7740.0,...,26870.0,27230.0,115670.0,116760.0,115450.0,116565.0,406678.365,406699.200,406657.530,406699.200
2019-01-02,70540.0,70590.0,69910.0,70060.0,96300.0,97670.0,95370.0,97410.0,7630.0,7770.0,...,26830.0,27410.0,116600.0,117085.0,113930.0,116635.0,406678.365,406720.035,406678.365,406699.200
2019-01-03,68930.0,70280.0,68250.0,70140.0,97430.0,97880.0,95590.0,96260.0,7750.0,7750.0,...,27130.0,27160.0,115325.0,115615.0,113075.0,113340.0,406720.035,406824.210,406678.365,406803.375
2019-01-04,70120.0,71320.0,70010.0,71270.0,96240.0,98700.0,95940.0,98620.0,7810.0,7850.0,...,27300.0,27950.0,113540.0,117520.0,112815.0,117055.0,406782.540,406782.540,406699.200,406720.035
2019-01-07,71290.0,71580.0,71220.0,71520.0,98730.0,99000.0,97750.0,98670.0,7840.0,7900.0,...,27550.0,27700.0,117350.0,118340.0,116395.0,117535.0,406720.035,406740.870,406699.200,406699.200

In [54]:
# 88 futures for training
futures = ['F_AD','F_AE','F_AH','F_AX','F_BC','F_BG','F_BO','F_BP',
               'F_C','F_CA','F_CC','F_CD','F_CF','F_CL','F_CT','F_DL',             
               'F_DM','F_DT','F_DX','F_DZ','F_EB','F_EC','F_ED','F_ES',
               'F_F','F_FB','F_FC','F_FL','F_FM','F_FP','F_FV','F_FY',             
               'F_GC','F_GD','F_GS','F_GX','F_HG','F_HO','F_HP','F_JY',
              'F_KC','F_LB','F_LC','F_LN','F_LQ','F_LR','F_LU','F_LX',
           'F_MD','F_MP','F_ND','F_NG','F_NQ','F_NR','F_NY','F_O',
             'F_OJ','F_PA','F_PL','F_PQ','F_RB','F_RF','F_RP','F_RR',
               'F_RU','F_RY','F_S','F_SB','F_SF','F_SH','F_SI','F_SM',
             'F_SS','F_SX','F_TR','F_TU','F_TY','F_UB','F_US','F_UZ','F_VF','F_VT','F_VW',
            'F_VX','F_W','F_XX','F_YM','F_ZQ'] 
len(futures)

# 85 futures for 2019 pred
futures_85 = ['F_AD','F_AE','F_AH','F_AX','F_BC','F_BG','F_BO','F_BP',
               'F_C','F_CA','F_CC','F_CD','F_CF','F_CL','F_CT','F_DL',             
               'F_DM','F_DT','F_DX','F_DZ','F_EB','F_EC','F_ED','F_ES',
               'F_F','F_FB','F_FC','F_FL','F_FM','F_FP','F_FV','F_FY',             
               'F_GC','F_GD','F_GS','F_GX','F_HG','F_HO','F_HP','F_JY',
              'F_KC','F_LB','F_LC','F_LN','F_LQ','F_LR','F_LU','F_LX',
           'F_MD','F_MP','F_ND','F_NG','F_NQ','F_NR','F_NY','F_O',
             'F_OJ','F_PA','F_PL','F_PQ','F_RB','F_RF','F_RP','F_RR',
               'F_RU','F_RY','F_S','F_SB','F_SF','F_SH','F_SI','F_SM',
             'F_SS','F_SX','F_TR','F_TU','F_TY','F_UB','F_US','F_UZ',
            'F_VX','F_W','F_XX','F_YM','F_ZQ']   #'F_VF','F_VT','F_VW',
len(futures_85)

85

In [52]:
indicator_pred = pd.read_pickle("./2019_test_44indic.pkl")
indicator_pred = indicator_pred.drop(['USA_BC', 'USA_BOT', 'USA_CCR', 'USA_CF', 'USA_CPICM', 'USA_GPAY'], axis=1)
indicator_pred = indicator_pred.fillna(method='bfill', axis=0)

In [57]:
new_features = pd.DataFrame(index=np.arange(len(pred_data)), columns=np.arange(85))
new_features.columns = futures_85
new_features["dates"] = (list(pred_data.index))
new_features = new_features.set_index("dates")
new_features.head()

,F_AD,F_AE,F_AH,F_AX,F_BC,F_BG,F_BO,F_BP,F_C,F_CA,...,F_TU,F_TY,F_UB,F_US,F_UZ,F_VX,F_W,F_XX,F_YM,F_ZQ
dates,,,,,,,,,,,,,,,,,,,,,
2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
from sklearn.preprocessing import StandardScaler
import lightgbm as lgb

os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\prediction_models')

scaler = StandardScaler()

count = 0
count_train = 0

# Build separate LGBM models for each individual future
for fut in futures:
    
    if fut == 'F_VF' or fut == 'F_VT' or fut == 'F_VW':
        count_train = count_train + 4
        continue
    
    # Lag features by 1 day
    x_train = train_data.shift(1).iloc[:,count_train:(count_train+4)]
    # combine with indicators
    combined_train = pd.concat([x_train, indicator_train], axis=1)
    combined_train = combined_train.dropna(axis=0)
    x_train = combined_train.iloc[:,0:4]
    x_train_exog = combined_train.iloc[:,4:]
    y_train = train_data.iloc[:,(count_train+3)]
    y_train = y_train.dropna(axis=0)
    y_train = y_train.drop(y_train.index[0])
    y_train = y_train.reset_index()
    train_dates = y_train.iloc[:,0]
    y_train = y_train.iloc[:,1]

    x_pred = pred_data.shift(1).iloc[:,count:(count+4)]
    combined_pred = pd.concat([x_pred, indicator_pred], axis=1)
    combined_pred = combined_pred.dropna(axis=0)
    x_pred = x_pred.dropna(axis=0)
    x_pred = combined_pred.iloc[:,0:4]
    x_pred_exog = combined_pred.iloc[:,4:]
    y_pred = pred_data.iloc[:,(count+3)]
    y_pred = y_pred.dropna(axis=0)
    y_pred = y_pred.drop(y_pred.index[0])
    y_pred = y_pred.reset_index()
    pred_dates = y_pred.iloc[:,0]
    y_pred = y_pred.iloc[:,1]

    x_train = scaler.fit_transform(x_train)
    x_pred = scaler.transform(x_pred)

    d_train = lgb.Dataset(x_train, label=y_train)

    #Set model params
    params = {}
    params['learning_rate'] = 0.5          
    params['boosting_type'] = 'gbdt'
    params['objective'] = 'regression'
    params['metric'] = 'mse'
    params['sub_feature'] = 0.8
    params['num_leaves'] = 20               
    params['min_data'] = 20
    params['max_depth'] = 20

    lgbmodel = lgb.train(params, d_train, 100)
    
    #Save models
    #filename = fut + ".txt"
    #lgbmodel.save_model(filename)

    #Predictions
    y_predicted = lgbmodel.predict(x_pred)

    #Store predictions to use for stack model
    for i in range(len(y_predicted)):
        new_features.at[pred_dates[i], fut] = y_predicted[i]

    count = count + 4
    count_train = count_train + 4
    
    print('Mean Absolute Error for ', fut, ': ', mean_absolute_percentage_error(y_pred, y_predicted))  
    print('Root Mean Squared Error for ', fut, ': ', rmse_ratio(y_pred, y_predicted))

Mean Absolute Error for  F_AD :  0.4372462217009919
Root Mean Squared Error for  F_AD :  1.5137273594363783
Mean Absolute Error for  F_AE :  0.6991479511013371
Root Mean Squared Error for  F_AE :  2.8807531706225813
Mean Absolute Error for  F_AH :  1.804406984456222
Root Mean Squared Error for  F_AH :  1.8778112392809094
Mean Absolute Error for  F_AX :  0.9452960182276556
Root Mean Squared Error for  F_AX :  6.648192243547146
Mean Absolute Error for  F_BC :  1.2239253500621359
Root Mean Squared Error for  F_BC :  4.043874770974066
Mean Absolute Error for  F_BG :  1.0773885164143209
Root Mean Squared Error for  F_BG :  3.30561563628044
Mean Absolute Error for  F_BO :  0.819649651773377
Root Mean Squared Error for  F_BO :  1.3471408291064502
Mean Absolute Error for  F_BP :  6.593353710244088
Root Mean Squared Error for  F_BP :  19.197813929490536
Mean Absolute Error for  F_C :  0.8166434703584474
Root Mean Squared Error for  F_C :  1.5256629838867697
Mean Absolute Error for  F_CA :  0.7316273487607738
Root Mean Squared Error for  F_CA :  2.1209724461338384
Mean Absolute Error for  F_CC :  1.1953088455101837
Root Mean Squared Error for  F_CC :  2.3128551013656105
Mean Absolute Error for  F_CD :  0.3409426904091613
Root Mean Squared Error for  F_CD :  1.1661163859396877
Mean Absolute Error for  F_CF :  0.49436629701582857
Root Mean Squared Error for  F_CF :  2.2970079581212177
Mean Absolute Error for  F_CL :  1.3880656025463465
Root Mean Squared Error for  F_CL :  4.025371740247438
Mean Absolute Error for  F_CT :  0.9684201085762437
Root Mean Squared Error for  F_CT :  2.3622892399536033
Mean Absolute Error for  F_DL :  0.7953331997352535
Root Mean Squared Error for  F_DL :  1.8844283075251282
Mean Absolute Error for  F_DM :  11.256182170540871
Root Mean Squared Error for  F_DM :  41.51799544750712
Mean Absolute Error for  F_DT :  3.429193814014083
Root Mean Squared Error for  F_DT :  14.109802034413395
Mean Absolute Error for  F_DX :  0.2762166093274802
Root Mean Squared Error for  F_DX :  1.0892515803432437
Mean Absolute Error for  F_DZ :  29.641351820297423
Root Mean Squared Error for  F_DZ :  48.07853238619988
Mean Absolute Error for  F_EB :  0.1346616310199233
Root Mean Squared Error for  F_EB :  0.6748631589725164
Mean Absolute Error for  F_EC :  0.37549254233291557
Root Mean Squared Error for  F_EC :  1.821014695667182
Mean Absolute Error for  F_ED :  0.029639200321999785
Root Mean Squared Error for  F_ED :  0.17920980985795973
Mean Absolute Error for  F_ES :  22.505417628787715
Root Mean Squared Error for  F_ES :  84.34293255374521
Mean Absolute Error for  F_F :  0.016789262403462863
Root Mean Squared Error for  F_F :  0.09266839197136012
Mean Absolute Error for  F_FB :  1.2299785600465756
Root Mean Squared Error for  F_FB :  1.3356439894924674
Mean Absolute Error for  F_FC :  0.7304103800650346
Root Mean Squared Error for  F_FC :  2.5401627149356707
Mean Absolute Error for  F_FL :  5.983858075712577
Root Mean Squared Error for  F_FL :  15.520308901374738
Mean Absolute Error for  F_FM :  2.4018564288317683
Root Mean Squared Error for  F_FM :  4.469997868859685
Mean Absolute Error for  F_FP :  11.995516498299699
Root Mean Squared Error for  F_FP :  24.710040387786606
Mean Absolute Error for  F_FV :  0.17605904203552505
Root Mean Squared Error for  F_FV :  0.7304709319966913
Mean Absolute Error for  F_FY :  0.7400704541600062
Root Mean Squared Error for  F_FY :  1.2799704378972223
Mean Absolute Error for  F_GC :  0.5171646905361733
Root Mean Squared Error for  F_GC :  2.7436220474026545
Mean Absolute Error for  F_GD :  0.7775698009285537
Root Mean Squared Error for  F_GD :  3.273371235499912
Mean Absolute Error for  F_GS :  0.4122390373236761
Root Mean Squared Error for  F_GS :  2.063681647158522
Mean Absolute Error for  F_GX :  4.964587134866464
Root Mean Squared Error for  F_GX :  22.389803559388238
Mean Absolute Error for  F_HG :  0.9815085740075776
Root Mean Squared Error for  F_HG :  3.323608703262733
Mean Absolute Error for  F_HO :  0.9962879803207249
Root Mean Squared Error for  F_HO :  3.6292968953727813
Mean Absolute Error for  F_HP :  2.176770002760332
Root Mean Squared Error for  F_HP :  6.236832630895845
Mean Absolute Error for  F_JY :  0.30291130903921787
Root Mean Squared Error for  F_JY :  1.3501935658649347
Mean Absolute Error for  F_KC :  1.4766849865296294
Root Mean Squared Error for  F_KC :  3.5289728603656956
Mean Absolute Error for  F_LB :  1.8832189000213009
Root Mean Squared Error for  F_LB :  4.623151745321352
Mean Absolute Error for  F_LC :  0.706321624085219
Root Mean Squared Error for  F_LC :  2.197859165897855
Mean Absolute Error for  F_LN :  2.3380945189443496
Root Mean Squared Error for  F_LN :  6.902733092398833
Mean Absolute Error for  F_LQ :  1.1102018668554985
Root Mean Squared Error for  F_LQ :  4.571598658951177
Mean Absolute Error for  F_LR :  1.1384699124641824
Root Mean Squared Error for  F_LR :  2.3810771693803416
Mean Absolute Error for  F_LU :  1.7333194248591053
Root Mean Squared Error for  F_LU :  6.097844216831551
Mean Absolute Error for  F_LX :  1.8593005114191734
Root Mean Squared Error for  F_LX :  6.035116892944952
Mean Absolute Error for  F_MD :  17.454907706917872
Root Mean Squared Error for  F_MD :  77.0812390489534
Mean Absolute Error for  F_MP :  11.988029076425317
Root Mean Squared Error for  F_MP :  19.324149441645165
Mean Absolute Error for  F_ND :  0.5007654123973292
Root Mean Squared Error for  F_ND :  1.678268848460178
Mean Absolute Error for  F_NG :  1.852815967126923
Root Mean Squared Error for  F_NG :  4.281984784361806
Mean Absolute Error for  F_NQ :  33.49532411151929
Root Mean Squared Error for  F_NQ :  126.64330866050693
Mean Absolute Error for  F_NR :  0.8666054398012744
Root Mean Squared Error for  F_NR :  1.6556034939318003
Mean Absolute Error for  F_NY :  0.9060194044678354
Root Mean Squared Error for  F_NY :  3.898403175080535
Mean Absolute Error for  F_O :  1.1139775991863305
Root Mean Squared Error for  F_O :  1.6784549391623669
Mean Absolute Error for  F_OJ :  1.3388023141140077
Root Mean Squared Error for  F_OJ :  2.221456005659382
Mean Absolute Error for  F_PA :  23.94257240744981
Root Mean Squared Error for  F_PA :  92.83235458057923
Mean Absolute Error for  F_PL :  0.9891461254571452
Root Mean Squared Error for  F_PL :  2.6430389718319116
Mean Absolute Error for  F_PQ :  0.9626313234367053
Root Mean Squared Error for  F_PQ :  2.7244200594807566
Mean Absolute Error for  F_RB :  1.8505833616807597
Root Mean Squared Error for  F_RB :  6.161918899141425
Mean Absolute Error for  F_RF :  0.805275010896014
Root Mean Squared Error for  F_RF :  3.384579319605917
Mean Absolute Error for  F_RP :  0.4966128661378551
Root Mean Squared Error for  F_RP :  2.0439002424250035
Mean Absolute Error for  F_RR :  1.0111476162076862
Root Mean Squared Error for  F_RR :  1.0739529297777788
Mean Absolute Error for  F_RU :  16.243101888942167
Root Mean Squared Error for  F_RU :  65.10139829354983
Mean Absolute Error for  F_RY :  0.3786089445894108
Root Mean Squared Error for  F_RY :  20.691898002027973
Mean Absolute Error for  F_S :  0.8835086098202926
Root Mean Squared Error for  F_S :  2.325796540411128
Mean Absolute Error for  F_SB :  1.452528200073939
Root Mean Squared Error for  F_SB :  2.1479533856933766
Mean Absolute Error for  F_SF :  0.36155997216829694
Root Mean Squared Error for  F_SF :  1.5695709508575644
Mean Absolute Error for  F_SH :  15.83928331771848
Root Mean Squared Error for  F_SH :  24.859102311150302
Mean Absolute Error for  F_SI :  0.7860622664606887
Root Mean Squared Error for  F_SI :  3.0191289448239598
Mean Absolute Error for  F_SM :  0.7512340205682364
Root Mean Squared Error for  F_SM :  1.7545973435423887
Mean Absolute Error for  F_SS :  0.010871659355641498
Root Mean Squared Error for  F_SS :  0.05455740870274865
Mean Absolute Error for  F_SX :  0.6167938623847865
Root Mean Squared Error for  F_SX :  2.4213239179992634
Mean Absolute Error for  F_TR :  2.03462469933612
Root Mean Squared Error for  F_TR :  5.392848020295187
Mean Absolute Error for  F_TU :  0.06999288912292491
Root Mean Squared Error for  F_TU :  0.418500436959092
Mean Absolute Error for  F_TY :  0.2859360547851243
Root Mean Squared Error for  F_TY :  1.3026636430613503

Mean Absolute Error for  F_UB :  1.295601535908299
Root Mean Squared Error for  F_UB :  4.773305187433576
Mean Absolute Error for  F_US :  0.45864172003707954
Root Mean Squared Error for  F_US :  2.2044474509170944
Mean Absolute Error for  F_UZ :  0.24580423067082274
Root Mean Squared Error for  F_UZ :  0.8356803522394479
Mean Absolute Error for  F_VX :  2.8053277710216813
Root Mean Squared Error for  F_VX :  5.0215069460923765
Mean Absolute Error for  F_W :  1.1692653594941078
Root Mean Squared Error for  F_W :  2.4913745391646516
Mean Absolute Error for  F_XX :  0.6287014528783532
Root Mean Squared Error for  F_XX :  1.480257860732005
Mean Absolute Error for  F_YM :  28.07439070444388
Root Mean Squared Error for  F_YM :  100.44017128781398
Mean Absolute Error for  F_ZQ :  0.14862405680503024
Root Mean Squared Error for  F_ZQ :  0.9497653835320116

In [68]:
new_features = new_features.iloc[1:,:]

In [59]:
new_features.head()

,F_AD,F_AE,F_AH,F_AX,F_BC,F_BG,F_BO,F_BP,F_C,F_CA,...,F_TU,F_TY,F_UB,F_US,F_UZ,F_VX,F_W,F_XX,F_YM,F_ZQ
dates,,,,,,,,,,,,,,,,,,,,,
2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-02,70816.8,97007,7829.24,260587,54088,51332.3,16652,87035.9,18726.6,47385.8,...,212230,122360,131114,146530,111615,24225.2,25116.8,27205,90664.1,407307
2019-01-03,69880.6,96378,7829.24,262362,55806.7,50880.3,16898.8,87035.9,18726.6,47119.7,...,212327,122070,131114,147346,111615,24277.2,25219.8,27216.3,90664.1,407307
2019-01-04,69949.4,96284.2,7829.24,260587,55353.5,52576.6,17008.7,87035.9,18894.2,46259.9,...,212920,122842,131114,149363,111615,24772,25669,27216.2,90664.1,407307
2019-01-07,70879.9,98772.3,7829.24,262871,57146.1,53456.8,17078.5,87035.9,19249.5,47183.9,...,211981,122527,131114,146955,111615,22336.7,25809.7,27241.6,90664.1,407307

In [69]:
os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\prediction_models\\csv_for_stacking')
new_features.to_csv("LGBM_Model_Predictions_(2019)V2.csv")