In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [11]:
# Read data
data = pd.read_csv("./F_AD.txt", low_memory=False, header=0)
feature_list = [' OPEN', ' HIGH', ' LOW']
output = ' CLOSE'
data = data[feature_list+[output]]

X = data.drop(output, axis=1)
y = data[output]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Logistic regression model
lr = LinearRegression()
model = lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred)) 
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

('Mean Absolute Error:', 134.47994155803804)
('Mean Squared Error:', 37285.163994605726)
('Root Mean Squared Error:', 193.09366637620647)

In [12]:
df

        Actual      Predicted
4354   82540.0   82664.086731
1342   72710.0   72723.680408
4148   74280.0   74301.031879
2529   65700.0   65714.251591
5734  101910.0  101679.897386
5199   88680.0   88909.269754
5816  102750.0  102563.219468
2481   63700.0   63878.548018
5253   97310.0   97534.157822
3954   76490.0   76611.318763
5176   89700.0   89692.573817
1145   73590.0   73425.465253
200    77960.0   77992.125623
2444   64940.0   64880.230281
3920   76400.0   76321.001664
7083   77610.0   77885.333081
119    77750.0   77796.779505
4082   70370.0   70821.556573
1381   72620.0   72515.420462
39     75400.0   75589.172332
3991   72690.0   72611.734840
6665   74180.0   74162.142446
5668  100750.0  100824.998766
6149   93080.0   93076.780167
5654  100960.0  100883.029421
4219   74990.0   74788.801773
5844  103930.0  103950.032225
6603   76520.0   76183.178001
2584   61190.0   61255.386201
2699   55900.0   56124.940593
...        ...            ...
1576   77000.0   76978.303150
4156   75390.0   75460.467632
5031   89170.0   89232.825174
6005   93230.0   93376.144522
2692   57760.0   57715.040285
580    76350.0   76361.550810
3943   76420.0   76401.855452
1703   79020.0   79006.096148
5881   98130.0   98162.065371
4      77200.0   77151.908986
366    74740.0   74704.147418
2298   65130.0   65176.676228
2746   51940.0   51960.025867
3022   50800.0   50852.089472
1998   68660.0   68728.067532
4974   90020.0   89884.853002
496    76780.0   76770.884105
268    77900.0   77855.232928
2435   63510.0   63625.804713
3160   54990.0   54872.892705
5329   99850.0   99593.724992
6534   71580.0   71485.555884
126    78630.0   78660.286215
3659   72750.0   72854.848903
3807   78670.0   78506.155595
2398   66860.0   66762.155602
4179   76420.0   76294.797254
1098   71340.0   71166.552103
4476   89230.0   89176.747680
4495   88420.0   89113.769115

[1467 rows x 2 columns]