In [33]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from helper_functions import *
import os

In [47]:
os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\prediction_models\\csv_for_stacking')

LR_data = pd.read_csv("./LR_Model_Predictions_(2016-2018).csv", low_memory=False, header=0)
LGBM_data = pd.read_csv("./LGBM_Predictions.csv", low_memory=False, header=0)
LSTM_data = pd.read_csv("./LSTM_predicted.csv", low_memory=False, header=0)
RF_data = pd.read_csv("./RF_predictions.csv", low_memory=False, header=0)
SARIMA_data = pd.read_csv("./SARIMA_Predictions.csv", low_memory=False, header=0)

In [48]:
# Standardize format
SARIMA_data.rename(columns=lambda x: x + "_SARIMA", inplace=True)
SARIMA_data.rename(columns={"Unnamed: 0_SARIMA":'DATE'}, inplace=True)
LGBM_data.rename(columns={"dates":'DATE'}, inplace=True)
LR_data["DATE"] = list(map(str, LR_data["DATE"]))
LR_data["DATE"] = LR_data["DATE"].apply(lambda x: x[0:4] + '-' + x[4:6] + '-' + x[6:8])

result = LGBM_data.set_index("DATE").join(LSTM_data.set_index("DATE"), on='DATE', lsuffix="_LGBM", rsuffix="_LSTM").reset_index()
result = result.set_index("DATE").join(RF_data.set_index("DATE"), on='DATE').reset_index()
result = result.set_index("DATE").join(LR_data.set_index("DATE"), on='DATE', lsuffix="_RF", rsuffix="_LR").reset_index()
result = result.set_index("DATE").join(SARIMA_data.set_index("DATE"), on='DATE').reset_index()

result = result.fillna(method='bfill')
result.head()

,DATE,F_AD_LGBM,F_AE_LGBM,F_AH_LGBM,F_AX_LGBM,F_BC_LGBM,F_BG_LGBM,F_BO_LGBM,F_BP_LGBM,F_C_LGBM,...,F_US_SARIMA,F_UZ_SARIMA,F_VF_SARIMA,F_VT_SARIMA,F_VW_SARIMA,F_VX_SARIMA,F_W_SARIMA,F_XX_SARIMA,F_YM_SARIMA,F_ZQ_SARIMA
0,2016-01-01,71296.911747,85901.674488,7829.242385,255484.549448,38365.514703,34013.656915,18215.556032,92581.499364,17829.692822,...,153750.0,111510.548466,128006.370234,147888.184302,112052.738638,18504.964587,23515.010887,30928.682762,86795.103351,414913.543865
1,2016-01-04,71296.911747,85901.674488,7829.242385,255484.549448,38365.514703,34013.656915,18215.556032,92581.499364,17829.692822,...,153750.0,111509.301163,128012.740785,147902.675392,112054.282462,18489.671922,23513.234782,30921.906748,86839.477543,414918.441300
2,2016-01-05,71296.911747,85901.674488,7829.242385,255484.549448,38365.514703,34013.656915,18215.556032,91997.118490,17829.692822,...,153750.0,111510.124515,128019.111653,147920.889259,112057.243954,18477.996683,23497.890472,30917.849244,86839.477543,414923.338792
3,2016-01-06,71050.233873,86663.424730,7829.242385,255484.549448,37032.812581,33906.859206,18056.948621,91401.078401,17792.318272,...,153750.0,111509.399341,128025.482838,147933.574103,112059.640625,18469.081644,23489.864373,30915.419424,86839.477543,414928.236342
4,2016-01-07,70580.112371,86786.813500,7829.242385,254367.179741,35499.680274,32161.040913,18000.390457,91797.971859,17730.697397,...,153750.0,111510.077885,128031.854340,147946.260034,112062.037346,18462.273359,23499.314896,30913.964274,86839.477543,414933.133950

In [49]:
all_x_train = result.loc[0:520,:]
all_x_test = result.loc[521:,:]

os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\data')

all_y_train = pd.read_pickle("data_base_test.pkl")
all_y_train = all_y_train.fillna(method='bfill')

all_y_test = pd.read_pickle("data_stack_test.pkl")
all_y_test = all_y_test.fillna(method='bfill')

C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)
C:\Users\Cheong\Anaconda3\lib\site-packages\pandas\core\indexes\base.py:162: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return cls.__new__(cls, **d)

In [50]:
futures = ['F_AD','F_AE','F_AH','F_AX','F_BC','F_BG','F_BO','F_BP',
               'F_C','F_CA','F_CC','F_CD','F_CF','F_CL','F_CT','F_DL',             
               'F_DM','F_DT','F_DX','F_DZ','F_EB','F_EC','F_ED','F_ES',
               'F_F','F_FB','F_FC','F_FL','F_FM','F_FP','F_FV','F_FY',             
               'F_GC','F_GD','F_GS','F_GX','F_HG','F_HO','F_HP','F_JY',
              'F_KC','F_LB','F_LC','F_LN','F_LQ','F_LR','F_LU','F_LX',
           'F_MD','F_MP','F_ND','F_NG','F_NQ','F_NR','F_NY','F_O',
             'F_OJ','F_PA','F_PL','F_PQ','F_RB','F_RF','F_RP','F_RR',
               'F_RU','F_RY','F_S','F_SB','F_SF','F_SH','F_SI','F_SM',
             'F_SS','F_SX','F_TR','F_TU','F_TY','F_UB','F_US','F_UZ',
            'F_VF','F_VT','F_VW','F_VX','F_W','F_XX','F_YM','F_ZQ']

In [51]:
final_preds = pd.DataFrame(index=np.arange(len(all_x_test)), columns=np.arange(len(futures)))
final_preds.columns = futures
final_preds["DATE"] = all_x_test["DATE"].values
final_preds = final_preds.set_index("DATE")
final_preds.head()

,F_AD,F_AE,F_AH,F_AX,F_BC,F_BG,F_BO,F_BP,F_C,F_CA,...,F_US,F_UZ,F_VF,F_VT,F_VW,F_VX,F_W,F_XX,F_YM,F_ZQ
DATE,,,,,,,,,,,,,,,,,,,,,
2018-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
for fut in futures:
    y_train = all_y_train[fut]['CLOSE']
    y_train = pd.DataFrame(y_train)
    y_train = y_train.fillna(method='ffill')
    y_test = all_y_test[fut]['CLOSE']
    y_test = pd.DataFrame(y_test)
    y_test = y_test.fillna(method='ffill')
    tempfut = fut + '_'
    feature_list = []
    for j in all_x_train.columns:
        if tempfut in j:
            feature_list.append(j)
    x_train = all_x_train.loc[:,feature_list]
    x_train = x_train.fillna(method='ffill')
    x_test = all_x_test.loc[:,feature_list]
    x_test = x_test.fillna(method='ffill')
    lr = LinearRegression()
    model = lr.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    
    #Store predictions 
    for i in range(len(final_preds.index.values)):
        final_preds.at[final_preds.index.values[i], fut] = y_pred[i][0]
    
    print('MAPE for ', fut, ': ', mean_absolute_percentage_error(y_test, y_pred))  
    print('RMSE for ', fut, ': ', rmse_ratio(y_test, y_pred))

MAPE for  F_AD :  CLOSE    0.446288
dtype: float64
RMSE for  F_AD :  CLOSE    1.559104
dtype: float64
MAPE for  F_AE :  CLOSE    0.820527
dtype: float64
RMSE for  F_AE :  CLOSE    3.258577
dtype: float64
MAPE for  F_AH :  CLOSE    0.57776
dtype: float64
RMSE for  F_AH :  CLOSE    0.698249
dtype: float64
MAPE for  F_AX :  CLOSE    0.918579
dtype: float64
RMSE for  F_AX :  CLOSE    6.40331
dtype: float64
MAPE for  F_BC :  CLOSE    1.970718
dtype: float64
RMSE for  F_BC :  CLOSE    6.364528
dtype: float64
MAPE for  F_BG :  CLOSE    1.418103
dtype: float64
RMSE for  F_BG :  CLOSE    4.363832
dtype: float64
MAPE for  F_BO :  CLOSE    0.939081
dtype: float64
RMSE for  F_BO :  CLOSE    1.53311
dtype: float64
MAPE for  F_BP :  CLOSE    0.484992
dtype: float64
RMSE for  F_BP :  CLOSE    1.809243
dtype: float64
MAPE for  F_C :  CLOSE    0.833863
dtype: float64
RMSE for  F_C :  CLOSE    1.592113
dtype: float64
MAPE for  F_CA :  CLOSE    0.762742
dtype: float64
RMSE for  F_CA :  CLOSE    2.155737
dtype: float64
MAPE for  F_CC :  CLOSE    2.120144
dtype: float64
RMSE for  F_CC :  CLOSE    3.996646
dtype: float64
MAPE for  F_CD :  CLOSE    0.363023
dtype: float64
RMSE for  F_CD :  CLOSE    1.256515
dtype: float64
MAPE for  F_CF :  CLOSE    0.149192
dtype: float64
RMSE for  F_CF :  CLOSE    0.854394
dtype: float64
MAPE for  F_CL :  CLOSE    1.589738
dtype: float64
RMSE for  F_CL :  CLOSE    5.253211
dtype: float64
MAPE for  F_CT :  CLOSE    1.14859
dtype: float64
RMSE for  F_CT :  CLOSE    3.145941
dtype: float64
MAPE for  F_DL :  CLOSE    0.719083
dtype: float64
RMSE for  F_DL :  CLOSE    1.906244
dtype: float64
MAPE for  F_DM :  CLOSE    0.852955
dtype: float64
RMSE for  F_DM :  CLOSE    3.777175
dtype: float64
MAPE for  F_DT :  CLOSE    0.598493
dtype: float64
RMSE for  F_DT :  CLOSE    3.13854
dtype: float64
MAPE for  F_DX :  CLOSE    0.310051
dtype: float64
RMSE for  F_DX :  CLOSE    1.182221
dtype: float64
MAPE for  F_DZ :  CLOSE    1.216258
dtype: float64
RMSE for  F_DZ :  CLOSE    2.417016
dtype: float64
MAPE for  F_EB :  CLOSE    0.004652
dtype: float64
RMSE for  F_EB :  CLOSE    0.030279
dtype: float64
MAPE for  F_EC :  CLOSE    0.378182
dtype: float64
RMSE for  F_EC :  CLOSE    1.816634
dtype: float64
MAPE for  F_ED :  CLOSE    0.022023
dtype: float64
RMSE for  F_ED :  CLOSE    0.174297
dtype: float64
MAPE for  F_ES :  CLOSE    1.011166
dtype: float64
RMSE for  F_ES :  CLOSE    4.684367
dtype: float64
MAPE for  F_F :  CLOSE    0.006297
dtype: float64
RMSE for  F_F :  CLOSE    0.040035
dtype: float64
MAPE for  F_FB :  CLOSE    1.096946
dtype: float64
RMSE for  F_FB :  CLOSE    1.309895
dtype: float64
MAPE for  F_FC :  CLOSE    0.846456
dtype: float64
RMSE for  F_FC :  CLOSE    3.054185
dtype: float64
MAPE for  F_FL :  CLOSE    0.770927
dtype: float64
RMSE for  F_FL :  CLOSE    2.688302
dtype: float64
MAPE for  F_FM :  CLOSE    0.91519
dtype: float64
RMSE for  F_FM :  CLOSE    1.664232
dtype: float64
MAPE for  F_FP :  CLOSE    0.871489
dtype: float64
RMSE for  F_FP :  CLOSE    2.16977
dtype: float64
MAPE for  F_FV :  CLOSE    0.172666
dtype: float64
RMSE for  F_FV :  CLOSE    0.692499
dtype: float64
MAPE for  F_FY :  CLOSE    0.674709
dtype: float64
RMSE for  F_FY :  CLOSE    1.204362
dtype: float64
MAPE for  F_GC :  CLOSE    0.504311
dtype: float64
RMSE for  F_GC :  CLOSE    2.375076
dtype: float64
MAPE for  F_GD :  CLOSE    0.907236
dtype: float64
RMSE for  F_GD :  CLOSE    3.951102
dtype: float64
MAPE for  F_GS :  CLOSE    0.391723
dtype: float64
RMSE for  F_GS :  CLOSE    1.626008
dtype: float64
MAPE for  F_GX :  CLOSE    0.60521
dtype: float64
RMSE for  F_GX :  CLOSE    3.180257
dtype: float64
MAPE for  F_HG :  CLOSE    1.003797
dtype: float64
RMSE for  F_HG :  CLOSE    3.499352
dtype: float64
MAPE for  F_HO :  CLOSE    1.23749
dtype: float64
RMSE for  F_HO :  CLOSE    4.655963
dtype: float64
MAPE for  F_HP :  CLOSE    2.022842
dtype: float64
RMSE for  F_HP :  CLOSE    5.579572
dtype: float64
MAPE for  F_JY :  CLOSE    0.33588
dtype: float64
RMSE for  F_JY :  CLOSE    1.44182
dtype: float64
MAPE for  F_KC :  CLOSE    1.498987
dtype: float64
RMSE for  F_KC :  CLOSE    3.836638
dtype: float64
MAPE for  F_LB :  CLOSE    2.344223
dtype: float64
RMSE for  F_LB :  CLOSE    6.549042
dtype: float64
MAPE for  F_LC :  CLOSE    1.02257
dtype: float64
RMSE for  F_LC :  CLOSE    2.911647
dtype: float64
MAPE for  F_LN :  CLOSE    1.928601
dtype: float64
RMSE for  F_LN :  CLOSE    4.899351
dtype: float64
MAPE for  F_LQ :  CLOSE    1.065598
dtype: float64
RMSE for  F_LQ :  CLOSE    4.416015
dtype: float64
MAPE for  F_LR :  CLOSE    1.263696
dtype: float64
RMSE for  F_LR :  CLOSE    2.515488
dtype: float64
MAPE for  F_LU :  CLOSE    0.975059
dtype: float64
RMSE for  F_LU :  CLOSE    3.760898
dtype: float64
MAPE for  F_LX :  CLOSE    0.753987
dtype: float64
RMSE for  F_LX :  CLOSE    2.610779
dtype: float64
MAPE for  F_MD :  CLOSE    0.822127
dtype: float64
RMSE for  F_MD :  CLOSE    4.696606
dtype: float64
MAPE for  F_MP :  CLOSE    0.700965
dtype: float64
RMSE for  F_MP :  CLOSE    1.495242
dtype: float64
MAPE for  F_ND :  CLOSE    0.4928
dtype: float64
RMSE for  F_ND :  CLOSE    1.626817
dtype: float64
MAPE for  F_NG :  CLOSE    1.838902
dtype: float64
RMSE for  F_NG :  CLOSE    5.69424
dtype: float64
MAPE for  F_NQ :  CLOSE    1.410723
dtype: float64
RMSE for  F_NQ :  CLOSE    6.263312
dtype: float64
MAPE for  F_NR :  CLOSE    1.209725
dtype: float64
RMSE for  F_NR :  CLOSE    2.890035
dtype: float64
MAPE for  F_NY :  CLOSE    1.035203
dtype: float64
RMSE for  F_NY :  CLOSE    4.41217
dtype: float64
MAPE for  F_O :  CLOSE    1.285708
dtype: float64
RMSE for  F_O :  CLOSE    1.913345
dtype: float64
MAPE for  F_OJ :  CLOSE    1.178248
dtype: float64
RMSE for  F_OJ :  CLOSE    2.20342
dtype: float64
MAPE for  F_PA :  CLOSE    1.628813
dtype: float64
RMSE for  F_PA :  CLOSE    6.847521
dtype: float64
MAPE for  F_PL :  CLOSE    1.188678
dtype: float64
RMSE for  F_PL :  CLOSE    3.155066
dtype: float64
MAPE for  F_PQ :  CLOSE    0.714326
dtype: float64
RMSE for  F_PQ :  CLOSE    2.112139
dtype: float64
MAPE for  F_RB :  CLOSE    1.652703
dtype: float64
RMSE for  F_RB :  CLOSE    5.833014
dtype: float64
MAPE for  F_RF :  CLOSE    0.261894
dtype: float64
RMSE for  F_RF :  CLOSE    1.296116
dtype: float64
MAPE for  F_RP :  CLOSE    0.356018
dtype: float64
RMSE for  F_RP :  CLOSE    1.539767
dtype: float64
MAPE for  F_RR :  CLOSE    0.825038
dtype: float64
RMSE for  F_RR :  CLOSE    0.933048
dtype: float64
MAPE for  F_RU :  CLOSE    1.086371
dtype: float64
RMSE for  F_RU :  CLOSE    5.320146
dtype: float64
MAPE for  F_RY :  CLOSE    0.432114
dtype: float64
RMSE for  F_RY :  CLOSE    23.255183
dtype: float64
MAPE for  F_S :  CLOSE    1.277538
dtype: float64
RMSE for  F_S :  CLOSE    3.399104
dtype: float64
MAPE for  F_SB :  CLOSE    1.999154
dtype: float64
RMSE for  F_SB :  CLOSE    2.921254
dtype: float64
MAPE for  F_SF :  CLOSE    0.426511
dtype: float64
RMSE for  F_SF :  CLOSE    1.899575
dtype: float64
MAPE for  F_SH :  CLOSE    1.134017
dtype: float64
RMSE for  F_SH :  CLOSE    2.253085
dtype: float64
MAPE for  F_SI :  CLOSE    1.051955
dtype: float64
RMSE for  F_SI :  CLOSE    3.734677
dtype: float64
MAPE for  F_SM :  CLOSE    1.206961
dtype: float64
RMSE for  F_SM :  CLOSE    2.946221
dtype: float64
MAPE for  F_SS :  CLOSE    0.012864
dtype: float64
RMSE for  F_SS :  CLOSE    0.066563
dtype: float64
MAPE for  F_SX :  CLOSE    0.701749
dtype: float64
RMSE for  F_SX :  CLOSE    2.656846
dtype: float64
MAPE for  F_TR :  CLOSE    1.011594
dtype: float64
RMSE for  F_TR :  CLOSE    2.477879
dtype: float64
MAPE for  F_TU :  CLOSE    0.057452
dtype: float64
RMSE for  F_TU :  CLOSE    0.338609
dtype: float64
MAPE for  F_TY :  CLOSE    0.304261
dtype: float64
RMSE for  F_TY :  CLOSE    1.237188
dtype: float64
MAPE for  F_UB :  CLOSE    0.10051
dtype: float64
RMSE for  F_UB :  CLOSE    0.507088
dtype: float64
MAPE for  F_US :  CLOSE    0.595819
dtype: float64
RMSE for  F_US :  CLOSE    2.684839
dtype: float64
MAPE for  F_UZ :  CLOSE    0.023606
dtype: float64
RMSE for  F_UZ :  CLOSE    0.114241
dtype: float64
MAPE for  F_VF :  CLOSE    0.064295
dtype: float64
RMSE for  F_VF :  CLOSE    0.307384
dtype: float64
MAPE for  F_VT :  CLOSE    0.133737
dtype: float64
RMSE for  F_VT :  CLOSE    0.670523
dtype: float64
MAPE for  F_VW :  CLOSE    0.010088
dtype: float64
RMSE for  F_VW :  CLOSE    0.060447
dtype: float64
MAPE for  F_VX :  CLOSE    4.174458
dtype: float64
RMSE for  F_VX :  CLOSE    9.735825
dtype: float64
MAPE for  F_W :  CLOSE    1.419855
dtype: float64
RMSE for  F_W :  CLOSE    2.918846
dtype: float64
MAPE for  F_XX :  CLOSE    0.728879
dtype: float64
RMSE for  F_XX :  CLOSE    1.670717
dtype: float64
MAPE for  F_YM :  CLOSE    0.903033
dtype: float64
RMSE for  F_YM :  CLOSE    4.291429
dtype: float64
MAPE for  F_ZQ :  CLOSE    0.01761
dtype: float64
RMSE for  F_ZQ :  CLOSE    0.216472
dtype: float64

In [55]:
os.chdir('C:\\Users\\Cheong\\Documents\\GitHub\\ARIMAMAS\\prediction_models\\csv_for_stacking')

final_preds.to_csv("Final_Predictions.csv", index=False)

In [57]:
all_x_test.head()

,DATE,F_AD_LGBM,F_AE_LGBM,F_AH_LGBM,F_AX_LGBM,F_BC_LGBM,F_BG_LGBM,F_BO_LGBM,F_BP_LGBM,F_C_LGBM,...,F_US_SARIMA,F_UZ_SARIMA,F_VF_SARIMA,F_VT_SARIMA,F_VW_SARIMA,F_VX_SARIMA,F_W_SARIMA,F_XX_SARIMA,F_YM_SARIMA,F_ZQ_SARIMA
521,2018-01-01,78333.293563,108571.222862,8869.279471,300757.296494,66456.907141,60124.632877,20154.452512,87035.878729,17730.697397,...,152829.056052,111965.471770,128042.742810,149521.873891,112275.664092,11709.052523,21329.004090,31327.815586,123495.950417,410570.447990
522,2018-01-02,78333.293563,108571.222862,8869.279471,300757.296494,66456.907141,60124.632877,20154.452512,87035.878729,17730.697397,...,152829.056052,111965.232796,128049.114691,149296.046776,112280.520332,11871.726350,21326.882213,31282.937254,123841.363500,410574.661099
523,2018-01-03,78333.293563,108571.222862,8869.279471,300757.296494,66456.907141,60124.632877,20154.452512,87035.878729,17730.697397,...,152829.056052,111967.366831,128055.486889,149179.860259,112282.974566,11999.133222,21360.108730,31255.354084,123841.363500,410578.874251
524,2018-01-04,78344.670161,109788.332420,8869.279471,300757.296494,67377.920132,61287.502726,20211.633309,87035.878729,17792.318272,...,152829.056052,111964.861935,128061.859404,149277.234753,112285.428853,12098.643035,21383.326464,31238.393334,123841.363500,410583.087447
525,2018-01-05,78657.706831,110512.910287,8869.279471,300757.296494,67433.674507,61366.069844,20307.890995,87035.878729,17437.864602,...,152160.276611,111947.884533,128066.380511,149470.539853,112282.004619,10948.925622,21700.000000,31636.431942,124503.475643,410499.481935